for i in ./ch4_conclusion/04_1_next_steps/README.md
./ch0_introduction/00_4_bitbucket_content_organization/README.md
./ch0_introduction/00_3_create_an_atlassian_account/README.md
./ch0_introduction/00_1_intro/README.md
./ch0_introduction/00_2_what_you_should_know/README.md
./ch2_working_with_branches_and_pull_requests/02_2_pushing_code_to_a_branch/README.md
./ch2_working_with_branches_and_pull_requests/02_1_creating_branches/README.md
./ch2_working_with_branches_and_pull_requests/02_4_challenge_create_and_merge_a_pull_request/README.md
./ch2_working_with_branches_and_pull_requests/02_3_pull_requests/README.md
./ch2_working_with_branches_and_pull_requests/02_5_solution_create_and_merge_a_pull_request/README.md
./ch1_getting_started_with_bitbucket/01_2_add_an_ssh_key_for_authentication/README.md
./ch1_getting_started_with_bitbucket/01_4_push_code_to_remote_repo/README.md
./ch1_getting_started_with_bitbucket/01_3_clone_repo_to_local_environment/README.md
./ch1_getting_started_with_bitbucket/01_1_public_and_private_repositories/README.md
./ch1_getting_started_with_bitbucket/01_6_solution_create_a_repo_and_add_code/README.md
./ch1_getting_started_with_bitbucket/01_5_challenge_create_a_repo_and_push_code/README.md
./ch3_working_with_jira_cloud/03_3_update_and_close_issues_from_bitbucket/README.md
./ch3_working_with_jira_cloud/03_2_create_an_issue_and_link_to_bitbucket_branch/README.md
./ch3_working_with_jira_cloud/03_5_solution_link_a_bitbucket_branch_to_jira_cloud/README.md
./ch3_working_with_jira_cloud/03_1_jira_cloud_intro/README.md
./ch3_working_with_jira_cloud/03_4_challenge_link_a_bitbucket_branch_to_jira_cloud/README.md

